services:
  - type: web
    name: employee-dashboard
    env: docker
    dockerfilePath: EmployeeDashboard/Dockerfile
    dockerContext: EmployeeDashboard
    dockerCommand: ""
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
    healthCheckPath: /Account/Login
    autoDeploy: true
